{
    "name": "Techdata OCR",
    "version": "19.0.1.3.0",
    "category": "Accounting/Accounting",
    "summary": "Advanced OCR provider for Odoo — AI-powered alternative to Odoo IAP",
    "author": "Techdata.solutions",
    "website": "https://techdata.solutions",
    "license": "OPL-1",
    "price": 0.0,
    "currency": "EUR",
    "images": ["static/description/banner.png"],
    "depends": [
        "account_invoice_extract",
        "hr_expense_extract",
        "web",
    ],
    "data": [
        "security/ocr_techdata_groups.xml",
        "security/ir.model.access.csv",
        "views/purchase_wizard.xml",
        "views/res_config_settings_views.xml",
        "views/product_mapping_views.xml",
        "views/reconcile_wizard.xml",
    ],
    "application": False,
    "installable": True,
    "auto_install": False,
    "post_init_hook": "post_init_hook",
}
